name: Security Hardened CI Pipeline
on: [push, pull_request]

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install safety
      - name: Scan for vulnerabilities
        run: safety check -r requirements.txt --full-report

  test:
    runs-on: ubuntu-latest
    needs: [dependency-scan]
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      FINE_APP_ID: ${{ secrets.FINE_APP_ID }}
      FINE_APP_SECRET: ${{ secrets.FINE_APP_SECRET }}
      AES_KEY: ${{ secrets.AES_KEY }}
      AES_IV: ${{ secrets.AES_IV }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest tests/ --junitxml=test-results.xml
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  security-test:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Bandit Security Scan
        uses: py-actions/bandit@v2
        with:
          args: src/ --recursive --format xml -o bandit-results.xml
      - name: Upload Bandit report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit-results.xml