name: Security Hardened CI Pipeline
on: [push, pull_request]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Dependency Scan
        run: |
          pip install safety
          safety check -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: [security-scan]
    env:
      FINE_APP_SECRET: ${{ secrets.FINE_APP_SECRET }}
      AES_KEY: ${{ secrets.AES_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true
      - run: pip install -r requirements.txt
      - run: pytest tests/ --allure-dir=./allure-results
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./allure-results